### ISSUE TITLE
插件加载出错

### ISSUE THREAD

**Issue by ElainaFanBoy** [bot-ssttkkl/nonebot-plugin-mahjong-utils#11]
请问这是咋回事

05-24 07:29:50 [ERROR] nonebot | Failed to import "nonebot_plugin_mahjong_utils"
Traceback (most recent call last):
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\bot.py", line 26, in <module>
    nonebot.load_plugins("src/plugins")
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_mahjong_utils\__init__.py", line 28, in <module>
    from . import matchers
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_mahjong_utils\matchers\__init__.py", line 1, in <module>
    from . import furo_judge_sniffer
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\plugins\nonebot_plugin_mahjong_utils\matchers\furo_judge_sniffer.py", line 12, in <module>
    from nonebot_plugin_mahjong_utils.mapper import send_furo_chance_shanten_result
ImportError: cannot import name 'send_furo_chance_shanten_result' from 'nonebot_plugin_mahjong_utils.mapper' (D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_mahjong_utils\mapper\__init__.py)

**Comment by ElainaFanBoy** [comment]
噢我知道咋回事了（）
